[2020-04-17 15:30:00,244] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atvt_inferencing.dummy_task 2020-04-17T06:29:32.856509+00:00 [queued]>
[2020-04-17 15:30:00,250] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atvt_inferencing.dummy_task 2020-04-17T06:29:32.856509+00:00 [queued]>
[2020-04-17 15:30:00,250] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-04-17 15:30:00,250] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2020-04-17 15:30:00,250] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-04-17 15:30:00,327] {taskinstance.py:887} INFO - Executing <Task(DummyOperator): dummy_task> on 2020-04-17T06:29:32.856509+00:00
[2020-04-17 15:30:00,338] {standard_task_runner.py:53} INFO - Started process 43437 to run task
[2020-04-17 15:30:00,475] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: atvt_inferencing.dummy_task 2020-04-17T06:29:32.856509+00:00 [running]> bi02.com
[2020-04-17 15:30:00,484] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=atvt_inferencing, task_id=dummy_task, execution_date=20200417T062932, start_date=20200417T063000, end_date=20200417T063000
[2020-04-17 15:30:09,472] {logging_mixin.py:112} INFO - [2020-04-17 15:30:09,472] {local_task_job.py:103} INFO - Task exited with return code 0
