[2020-04-17 13:56:41,394] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atvt_inferencing.at_gateway_inference_task 2020-04-17T04:54:00+00:00 [queued]>
[2020-04-17 13:56:41,401] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atvt_inferencing.at_gateway_inference_task 2020-04-17T04:54:00+00:00 [queued]>
[2020-04-17 13:56:41,401] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-04-17 13:56:41,401] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-04-17 13:56:41,401] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-04-17 13:56:41,480] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): at_gateway_inference_task> on 2020-04-17T04:54:00+00:00
[2020-04-17 13:56:41,492] {standard_task_runner.py:53} INFO - Started process 28297 to run task
[2020-04-17 13:56:41,639] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: atvt_inferencing.at_gateway_inference_task 2020-04-17T04:54:00+00:00 [running]> bi02.com
[2020-04-17 13:57:01,148] {taskinstance.py:1128} ERROR - unsupported operand type(s) for +: 'float' and 'str'
Traceback (most recent call last):
  File "/home/chkimsu/anaconda3/envs/csb2/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/chkimsu/anaconda3/envs/csb2/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/chkimsu/anaconda3/envs/csb2/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/data01/CSB/CSB_Jupyter/ATVT/ariflow/dags/.ipynb_checkpoints/Inferencing_airflow-module-checkpoint.py", line 165, in at_gateway_inference_task
    file.writelines(line+'\n')
TypeError: unsupported operand type(s) for +: 'float' and 'str'
[2020-04-17 13:57:01,149] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=atvt_inferencing, task_id=at_gateway_inference_task, execution_date=20200417T045400, start_date=20200417T045641, end_date=20200417T045701
[2020-04-17 13:57:02,835] {logging_mixin.py:112} INFO - [2020-04-17 13:57:02,835] {local_task_job.py:103} INFO - Task exited with return code 1
